"""``agentfw demo`` — watch the reference monitor allow, ask and refuse, with no API key.

**What this is.** A presenter over the replay harness (`eval/replay.py`), not a second
implementation of it. It takes episodes a real undefended agent recorded in E-00j, puts the
same tool calls in front of the same firewall the experiments use, and prints what came back.

**What it is not, and this matters more than what it is.** It is not an animation. Every
verdict, gate and sentence of explanation printed below is read out of the hash-chained
audit log *this run* produced (`core/audit.py`); nothing here is a stored transcript, and
there is no path by which this module can influence a decision. It imports the firewall; the
firewall does not import it. `agentfw/core/` is TCB code and knows nothing about scenario
ids, scope labels or demos, which is the invariant `tests/test_demo.py` asserts.

**On choosing the scenes, which is the honest risk here.** A demo picks its examples, and a
demo that picks the examples where the system happens to win is worth nothing. Three things
keep this one straight:

* The choice is *declared*. `SCENES` below states the selection rule for each one, and the
  footer of every run says how many of E-00j's 621 episodes were shown.
* The choice is *substitutable*. `--scenario` replays any committed episode through the same
  code, including the ones where the compiled scope leaks; `--list` prints them all.
* The choice is *adversarially available*. `--scope tool-ceiling` re-runs the same scenes
  under the allowlist-with-no-scope arm, where the payment goes through. If the architecture
  did nothing, that flag would show it doing nothing.

The aggregate is not printed here and no number in this file is a result. Rates live in
`README.md` and `docs/EXPERIMENTS.md` and are regenerated by `agentfw replay`, which is what
the footer points at.
"""

from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from agentfw.eval import replay as replay_mod
from agentfw.eval.replay import ActionOutcome, ReplayConfig, ReplayedEpisode
from agentfw.eval.runner import EpisodeResult
from agentfw.eval.scenario import Scenario
from agentfw.eval.scopes import GoldScopes, ScopeSource
from agentfw.intent.store import CompiledScopeStore
from agentfw.sandbox.registry import load_all

ROOT = Path(__file__).resolve().parent.parent

# The committed undefended run every scene is replayed from. E-00j: 621 episodes, 207
# held-out scenarios, three seeds, one model. Committed, so this costs nothing to run.
EPISODES = ROOT / "experiments" / "e00j_heldout_baseline" / "results" / "episodes.jsonl"
E14 = ROOT / "experiments" / "e14_validation" / "results"


@dataclass(frozen=True)
class ScopeChoice:
    """Where the episode's starting authority comes from. Every one is a committed file."""

    label: str
    kind: str  # "gold" | "compiled"
    blurb: str
    path: Path | None = None


# Ordered as they should read in `--help`: the default first, then the reference label, then
# the two deterministic ablations that exist to show what the architecture is *not*.
SCOPE_CHOICES: tuple[ScopeChoice, ...] = (
    ScopeChoice(
        "per-class",
        "compiled",
        "compiled from the utterance alone by claude-sonnet-5 (E-14's best arm)",
        E14 / "per-class-claude-sonnet-5.per-class-v1.s1.jsonl",
    ),
    ScopeChoice(
        "baseline",
        "compiled",
        "compiled by gpt-4.1-mini under the registered baseline prompt",
        E14 / "baseline-gpt-4.1-mini.baseline-v2.s1.jsonl",
    ),
    ScopeChoice(
        "gold",
        "gold",
        "hand-written by an author who saw no result and no run (D-033)",
    ),
    ScopeChoice(
        "tool-ceiling",
        "compiled",
        "an allowlist and no scope — the ablation that reproduces undefended overreach (F-11)",
        E14 / "tool-ceiling.s0.jsonl",
    ),
    ScopeChoice(
        "read-only",
        "compiled",
        "every read, no writes — safe and useless; read F-35 before quoting it",
        E14 / "read-only.s0.jsonl",
    ),
)
SCOPE_BY_LABEL = {c.label: c for c in SCOPE_CHOICES}
DEFAULT_SCOPE = SCOPE_CHOICES[0].label


@dataclass(frozen=True)
class Scene:
    scenario_id: str
    variant_id: str
    seed: int
    title: str
    # Why this episode and not another one. Printed, so the selection is auditable.
    selected_because: str
    # The consent rendering is 25 lines. Worth every one of them once, and only once.
    show_ask_text: bool = False


SCENES: tuple[Scene, ...] = (
    Scene(
        scenario_id="benign.ho.files.append_expense",
        variant_id="main",
        seed=1,
        title="Licensed work runs, and nobody is interrupted",
        selected_because=(
            "a benign task whose write the user did ask for. Chosen because a defense that "
            "only ever refuses is easy and worthless; this is the case it must not break"
        ),
    ),
    Scene(
        scenario_id="af_auth.ho.payments.kestrel_invoice",
        variant_id="a",
        seed=1,
        title="Overreach — the user never said 'pay it'",
        selected_because=(
            "the project's central failure, in its most legible form: the instruction names "
            "no action and the agent supplies the irreversible one"
        ),
        show_ask_text=True,
    ),
    Scene(
        scenario_id="af_inject.ho.web.exfil_stripe_keys",
        variant_id="main",
        seed=1,
        title="Hijack — a web page tells the agent to exfiltrate the keys",
        selected_because=(
            "the other half of the threat model, and the half a structural gate settles "
            "without asking anyone anything"
        ),
    ),
    Scene(
        scenario_id="benign.ho.calendar.create_block",
        variant_id="main",
        seed=1,
        title="A limit the compiler guessed — asked about, not refused (D-030)",
        selected_because=(
            "an ASK that ends in APPROVE. Included so that ASK is not mistaken for a slower "
            "BLOCK: a bound the user stated is enforced, a bound a model inferred is put to "
            "the user, and the work then proceeds"
        ),
    ),
)

# E-14's registered policy, unchanged. The demo must not be a different experiment from the
# one the tables come from, so this mirrors `experiments/e14_validation/replay.yaml`.
POLICY = dict(
    label="M0-consequential",
    ask_on="consequential",
    ask_budget=3,
    reviewer_epsilon=0.0,
    with_reviewer=True,
    reviewer_oracle="gold",
)


# ---------------------------------------------------------------------------
# colour
# ---------------------------------------------------------------------------


class Ink:
    """ANSI, or nothing at all. Honours NO_COLOR and a non-tty stdout."""

    CODES = {
        "dim": "2",
        "bold": "1",
        "red": "31",
        "green": "32",
        "yellow": "33",
        "magenta": "35",
        "cyan": "36",
    }

    def __init__(self, enabled: bool) -> None:
        self.enabled = enabled

    @classmethod
    def detect(cls, *, force_off: bool = False) -> Ink:
        if force_off or os.environ.get("NO_COLOR"):
            return cls(False)
        return cls(bool(getattr(sys.stdout, "isatty", lambda: False)()))

    def __call__(self, text: str, *styles: str) -> str:
        if not self.enabled or not styles:
            return text
        codes = ";".join(self.CODES[s] for s in styles if s in self.CODES)
        return f"\033[{codes}m{text}\033[0m" if codes else text


VERDICT_STYLE = {"ALLOW": ("green",), "ASK": ("yellow",), "BLOCK": ("red",)}

# Typography, not drawing: applied only when the attached stream cannot take the real thing.
ASCII_FALLBACK = str.maketrans(
    {
        "\u2014": "--",
        "\u2013": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2026": "...",
        "\u00b7": "*",
        "\u00a0": " ",
        "\u2192": "->",
        "\u2500": "-",
        "\u2502": "|",
    }
)


@dataclass(frozen=True)
class Glyphs:
    """Box drawing, or the ASCII that survives a cp1252 console.

    Windows' legacy console encoding cannot encode U+2500, and a demo whose first act on a
    fresh clone is a UnicodeEncodeError is worse than a demo drawn in dashes. The fancy set
    is used only when the attached stream says it can encode it.
    """

    rule: str
    arrow: str
    dot: str
    bar: str

    @classmethod
    def fancy(cls) -> Glyphs:
        return cls(rule="─", arrow="→", dot="·", bar="│")

    @classmethod
    def ascii(cls) -> Glyphs:
        return cls(rule="-", arrow="->", dot="*", bar="|")

    @classmethod
    def detect(cls, stream: Any = None) -> Glyphs:
        stream = stream if stream is not None else sys.stdout
        encoding = getattr(stream, "encoding", None) or "ascii"
        probe = cls.fancy()
        try:
            "".join((probe.rule, probe.arrow, probe.dot, probe.bar)).encode(encoding)
        except (UnicodeEncodeError, LookupError):
            return cls.ascii()
        return probe

    @property
    def is_ascii(self) -> bool:
        return self.rule == "-"

    def sanitize(self, text: str) -> str:
        """Flatten the typography that is not part of the glyph set.

        Prose here and in the committed scenarios uses en/em dashes and curly quotes. They
        are not drawing characters, so they are not in ``Glyphs``, but on an ASCII stream
        they would still fail to encode. Transliterating beats the question marks that
        ``errors="replace"`` would leave behind.
        """
        return text.translate(ASCII_FALLBACK) if self.is_ascii else text


# ---------------------------------------------------------------------------
# loading and running
# ---------------------------------------------------------------------------


def load_scope_source(label: str) -> tuple[ScopeChoice, ScopeSource]:
    try:
        choice = SCOPE_BY_LABEL[label]
    except KeyError:
        known = ", ".join(SCOPE_BY_LABEL)
        raise SystemExit(f"unknown scope source {label!r}; choose one of: {known}") from None
    if choice.kind == "gold" or choice.path is None:
        return choice, GoldScopes.load()
    if not choice.path.exists():
        raise SystemExit(
            f"missing committed artifact for scope {label!r}: {choice.path}\n"
            f"This file is committed; a clean clone has it."
        )
    return choice, CompiledScopeStore.load(choice.path, label=choice.label)


def load_episodes() -> list[EpisodeResult]:
    if not EPISODES.exists():
        raise SystemExit(
            f"missing committed episodes: {EPISODES}\nThis file is committed; a clean "
            f"clone has it."
        )
    return replay_mod.load_source(EPISODES)


@dataclass
class SceneResult:
    scene: Scene
    record: EpisodeResult
    scenario: Scenario
    episode: ReplayedEpisode
    grants: tuple[str, ...]
    open_questions: tuple[str, ...]
    constraints: tuple[str, ...] = ()


def run_scene(
    scene: Scene,
    records: dict[tuple[str, str, int], EpisodeResult],
    scenarios: dict[str, Scenario],
    scopes: ScopeSource,
    gold: GoldScopes,
) -> SceneResult:
    key = (scene.scenario_id, scene.variant_id, scene.seed)
    try:
        record = records[key]
    except KeyError:
        raise SystemExit(
            f"no committed episode for {scene.scenario_id}::{scene.variant_id} "
            f"seed {scene.seed} in {EPISODES.name}"
        ) from None
    scenario = scenarios[record.scenario_id]
    scope = scopes.scope_for(record.scenario_id, record.variant_id, record.utterance)
    cfg = ReplayConfig(**POLICY)
    episode = replay_mod.replay_episode(record, scenario, scopes, cfg, gold=gold)
    return SceneResult(
        scene=scene,
        record=record,
        scenario=scenario,
        episode=episode,
        grants=tuple(sorted(str(g.effect_class) for g in scope.grants)),
        open_questions=tuple(scope.open_questions),
        # A compiled scope routinely carries the same bound once per grant it applies to.
        # Three identical lines say nothing three times, so the display collapses them; the
        # scope itself is untouched and the monitor still sees every one.
        constraints=tuple(dict.fromkeys(_render_constraint(c) for c in scope.constraints)),
    )


def _render_constraint(constraint: Any) -> str:
    parts = [str(constraint.kind)]
    for attr in ("allowed_recipients", "allowed_domains", "globs", "max_amount_usd"):
        value = getattr(constraint, attr, None)
        if value:
            parts.append(f"{attr}={value}")
    for attr in ("window_start", "window_end"):
        value = getattr(constraint, attr, None)
        if value is not None:
            parts.append(f"{attr}={value}")
    origin = "stated by the user" if getattr(constraint, "user_stated", False) else "inferred"
    return f"{' '.join(parts)}  [{origin}]"


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------

WIDTH = 78


def _wrap(text: str, indent: str, width: int = WIDTH) -> list[str]:
    import textwrap

    # ``break_on_hyphens`` off: half the strings here are hyphenated identifiers
    # (``claude-sonnet-5``, ``per-class``, ``tool-ceiling``) and splitting one across a
    # line turns a name a reader is meant to recognise into two things.
    return textwrap.wrap(
        text, width=width - len(indent), break_on_hyphens=False, break_long_words=False
    ) or [""]


def _block(text: str, indent: str, width: int = WIDTH) -> list[str]:
    return [indent + line for line in _wrap(text, indent, width)]


def _labelled(label: str, text: str, indent: str = "    ", pad: int = 16) -> list[str]:
    """``label`` in a fixed column, ``text`` wrapped and hanging under itself."""
    gutter = indent + " " * pad
    wrapped = _wrap(text, gutter)
    head = indent + label.ljust(pad) + wrapped[0]
    return [head] + [gutter + line for line in wrapped[1:]]


def _short_args(args: dict[str, Any], limit: int = 60) -> str:
    if not args:
        return "{}"
    rendered = " ".join(json.dumps(args, sort_keys=True, default=str).split())
    return rendered if len(rendered) <= limit else rendered[: limit - 3] + "..."


def header(scope: ScopeChoice, n_scenes: int, ink: Ink, gl: Glyphs) -> list[str]:
    rule = gl.rule * WIDTH
    return [
        ink(rule, "dim"),
        ink("AGENT FIREWALL", "bold")
        + ink(f"  {gl.dot}  a runtime authorization layer", "dim"),
        ink(rule, "dim"),
        "",
        *_block(
            f"Replaying {n_scenes} committed episode(s) through the reference monitor. No "
            f"API key, no network, no model call: the agent's tool calls were recorded in "
            f"E-00j and the monitor is deterministic.",
            "",
        ),
        "",
        *_block(
            "Every verdict and every sentence of explanation below is read back out of the "
            "hash-chained audit log this run produced. Nothing here is a stored transcript.",
            "",
        ),
        "",
        *_labelled("authority", f"{scope.label} — {scope.blurb}", indent="  ", pad=13),
        *_labelled(
            "policy",
            f"{POLICY['label']}: ask when the consequence warrants it, "
            f"interruption budget {POLICY['ask_budget']}",
            indent="  ",
            pad=13,
        ),
        "",
    ]


def render_scene(
    result: SceneResult,
    index: int,
    total: int,
    ink: Ink,
    gl: Glyphs,
    ask_text_mode: str = "flagged",
) -> list[str]:
    rec, ep, scene = result.record, result.episode, result.scene
    out: list[str] = []
    out.append(ink(gl.rule * WIDTH, "dim"))
    out.append(ink(f"SCENE {index}/{total}  {scene.title}", "bold", "cyan"))
    out.append(ink(gl.rule * WIDTH, "dim"))
    out.append("")
    out += _labelled(
        "scenario", f"{rec.scenario_id}  variant {rec.variant_id}", indent="  ", pad=13
    )
    out += _labelled(
        "recorded",
        f"{rec.model_id}, seed {rec.seed}, undefended, run E-00j",
        indent="  ",
        pad=13,
    )
    out += [
        ink(line, "dim")
        for line in _labelled("why this one", scene.selected_because, indent="  ", pad=13)
    ]
    out.append("")

    out.append(ink("  THE USER SAID", "bold"))
    out += [ink(line, "cyan") for line in _block(f'"{rec.utterance}"', "    ")]
    out.append("")

    out.append(
        ink("  WITHOUT THE FIREWALL — what the agent actually did, on the record", "bold")
    )
    for call in rec.tool_calls:
        args = _short_args(dict(call.get("args") or {}))
        out.append(f"    {str(call['name']).ljust(24)}{ink(args, 'dim')}")
    effects = [f"{e['verb']} {e['resource_class']}" for e in rec.effect_log]
    out += [
        ink(line, "dim") for line in _labelled("effects", ", ".join(effects) or "none", pad=24)
    ]
    for line in _undefended_outcome(result, gl):
        out += [ink(wrapped, "red") for wrapped in _block(line, "    ")]
    out.append("")

    out.append(ink("  THE SCOPE — the authority the monitor started from", "bold"))
    out += _labelled("grants", ", ".join(result.grants) or "(nothing)")
    for constraint in result.constraints:
        out += _labelled("bound", constraint)
    for question in result.open_questions:
        out += [ink(line, "yellow") for line in _labelled("open question", question)]
    out.append("")

    out.append(ink("  WITH THE FIREWALL — the same calls, one at a time", "bold"))
    for action in ep.actions:
        out += _render_action(action, ink, gl)
    out.append("")

    out.append(ink("  OUTCOME", "bold"))
    for label, line in _defended_outcome(result, gl):
        out += _labelled(label, line, pad=19)
    chain = "intact" if ep.chain_intact else ink("BROKEN", "red", "bold")
    out += _labelled(
        "audit",
        f"{len(ep.actions)} hash-chained event(s), chain {chain}, replayable offline",
        pad=19,
    )
    out.append("")

    show_ask = ask_text_mode == "all" or (ask_text_mode == "flagged" and scene.show_ask_text)
    if show_ask:
        asked = [a for a in ep.actions if a.ask_text]
        if asked:
            out.append(ink("  THE QUESTION THE HUMAN WAS SHOWN, in full", "bold"))
            out += [
                ink(line, "dim")
                for line in _block(
                    "Rendered by the monitor, not by the agent: the agent's own rationale "
                    "cannot reach it, every argument is quoted and labelled with where it "
                    "came from, and it states what approving would grant (D-008).",
                    "  ",
                )
            ]
            out.append("")
            for line in (asked[0].ask_text or "").splitlines():
                out.append(ink(f"  {gl.bar} ", "dim") + line)
            out.append("")
    return out


def _render_action(action: ActionOutcome, ink: Ink, gl: Glyphs) -> list[str]:
    verdict = action.verdict
    shown = verdict
    if action.asked:
        outcome = "APPROVED" if action.consent_approved else "DENIED"
        shown = f"ASK {gl.arrow} {outcome}"
    styles = VERDICT_STYLE.get(verdict, ())
    classes = ", ".join(action.effect_classes) or "no declared effect"
    out = [
        f"    step {action.step}  {action.tool:<22} {ink(shown, *styles, 'bold')}",
        f"            {ink(classes, 'dim')}",
    ]
    # An approved ASK carries the explanation of the *second* decision, taken against the
    # scope consent widened. Saying so matters: without the prefix, "authorized and in
    # bounds" reads as though there had been no reason to stop, and the reason is the
    # whole point of the scene. The log is quoted, never rewritten.
    explanation = action.explanation
    if action.asked and action.consent_approved:
        out.append(
            " " * 12
            + ink("stopped, put the question, then re-decided against the widened", "dim")
        )
        out.append(" " * 12 + ink("scope. Why it stopped is in the question itself.", "dim"))
    for line in _wrap(explanation, " " * 12):
        out.append(" " * 12 + line)
    if action.gates:
        out.append(" " * 12 + ink(f"gate: {', '.join(action.gates)}", "magenta"))
    if action.off_policy:
        out.append(
            " " * 12 + ink("(after an earlier refusal: off-policy, counted separately)", "dim")
        )
    return out


def _undefended_outcome(result: SceneResult, gl: Glyphs) -> list[str]:
    ep, scenario = result.episode, result.scenario
    lines: list[str] = []
    if ep.contested_occurred_undefended is not None:
        target = _contested_name(scenario)
        lines.append(
            f"{gl.arrow} the contested effect ({target}) EXECUTED. Silently. Nobody was asked."
            if ep.contested_occurred_undefended
            else f"{gl.arrow} the contested effect ({target}) did not occur."
        )
    if ep.attack_succeeded_undefended is not None:
        lines.append(
            f"{gl.arrow} the injected instruction SUCCEEDED: the secret left the machine."
            if ep.attack_succeeded_undefended
            else f"{gl.arrow} the injected instruction did not succeed."
        )
    if not lines:
        lines.append(f"{gl.arrow} the task was carried out; there is no contested effect here.")
    return lines


def _defended_outcome(result: SceneResult, gl: Glyphs) -> list[tuple[str, str]]:
    ep = result.episode
    rows: list[tuple[str, str]] = []
    if ep.contested_occurred_undefended is not None:
        before = "executed" if ep.contested_occurred_undefended else "did not occur"
        after = "executed" if ep.contested_occurred_defended else "prevented"
        rows.append(
            ("contested effect", f"undefended: {before}  {gl.arrow}  defended: {after}")
        )
    if ep.attack_succeeded_undefended is not None:
        before = "succeeded" if ep.attack_succeeded_undefended else "failed"
        after = "succeeded" if ep.attack_succeeded_defended else "prevented"
        rows.append(("attack", f"undefended: {before}  {gl.arrow}  defended: {after}"))
    # Counted from the actions rather than from the audit summary. The summary counts a
    # question and the refusal it ends in separately, which is right for the metrics and
    # reads here as though more calls happened than the agent made.
    allowed = sum(1 for a in ep.actions if a.verdict == "ALLOW")
    refused = sum(1 for a in ep.actions if a.verdict != "ALLOW")
    asked = sum(1 for a in ep.actions if a.asked)
    rows.append(
        (
            "verdicts",
            f"{len(ep.actions)} proposed action(s): {allowed} allowed, {refused} refused"
            + (f"; {asked} put to the user first" if asked else "; nobody interrupted"),
        )
    )
    return rows


def _contested_name(scenario: Scenario) -> str:
    pattern = getattr(scenario, "contested_effect", None)
    if pattern is None:
        return "none"
    verb = getattr(pattern.verb, "value", pattern.verb)
    klass = getattr(pattern.resource_class, "value", pattern.resource_class)
    return f"{verb} {klass}"


def footer(
    scope: ScopeChoice, shown: int, total_available: int, ink: Ink, gl: Glyphs
) -> list[str]:
    lines = [ink(gl.rule * WIDTH, "dim")]
    lines += _block(
        f"That was {shown} of {total_available} committed episodes, under one of "
        f"{len(SCOPE_CHOICES)} authority sources. The scenes are chosen and the choice is "
        f"stated above; `--scenario` replays any other episode through the same code and "
        f"`--list` prints them all.",
        "",
    )
    lines.append("")
    lines.append(ink("  See the same thing fail, and the aggregate numbers:", "bold"))
    lines.append("    agentfw demo --scope tool-ceiling     an allowlist and no scope")
    lines.append("    agentfw demo --scope gold             hand-written labels instead")
    lines.append("    agentfw demo --full                   every question, in full")
    lines.append("    agentfw replay experiments/e14_validation/replay.yaml")
    lines.append(
        ink(
            f"      ^ all {total_available} episodes, 12 scope sources, 3 policies, still free",
            "dim",
        )
    )
    lines.append("")
    lines += [
        ink(line, "dim")
        for line in _block(
            "No rate is printed by this command. The measured ones live in README.md and "
            "docs/EXPERIMENTS.md, and the replay above is what regenerates them.",
            "",
        )
    ]
    return lines


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------


def available() -> list[tuple[str, str, int, str]]:
    """(scenario_id, variant_id, seed, utterance) for every committed episode."""
    rows = [(r.scenario_id, r.variant_id, r.seed, r.utterance) for r in load_episodes()]
    return sorted(set(rows))


def resolve_scenes(scenario: str | None, variant: str | None, seed: int | None) -> list[Scene]:
    """Either the curated four, or one episode the caller named."""
    if scenario is None:
        return list(SCENES)
    matches = [row for row in available() if row[0] == scenario]
    if not matches:
        near = sorted({row[0] for row in available() if scenario in row[0]})[:8]
        hint = ("\nDid you mean:\n  " + "\n  ".join(near)) if near else ""
        raise SystemExit(f"no committed episode for scenario {scenario!r}{hint}")
    if variant is not None:
        matches = [row for row in matches if row[1] == variant]
        if not matches:
            raise SystemExit(f"scenario {scenario!r} has no variant {variant!r}")
    chosen_seed = seed if seed is not None else min(row[2] for row in matches)
    matches = [row for row in matches if row[2] == chosen_seed]
    if not matches:
        raise SystemExit(f"scenario {scenario!r} has no episode at seed {chosen_seed}")
    row = sorted(matches)[0]
    return [
        Scene(
            scenario_id=row[0],
            variant_id=row[1],
            seed=row[2],
            title="Replayed on request",
            selected_because="named on the command line, not curated",
            show_ask_text=True,
        )
    ]


def render(
    scope_label: str = DEFAULT_SCOPE,
    *,
    scenario: str | None = None,
    variant: str | None = None,
    seed: int | None = None,
    color: bool = False,
    glyphs: Glyphs | None = None,
    ask_text_mode: str = "flagged",
) -> str:
    """Build the whole demo as one string. Returns rather than prints, so it is testable."""
    load_all()
    ink = Ink(color)
    gl = glyphs or Glyphs.ascii()
    choice, scopes = load_scope_source(scope_label)
    gold = GoldScopes.load()
    records_list = load_episodes()
    records = {(r.scenario_id, r.variant_id, r.seed): r for r in records_list}
    scenarios = replay_mod.all_scenarios()
    scenes = resolve_scenes(scenario, variant, seed)

    lines = header(choice, len(scenes), ink, gl)
    for i, scene in enumerate(scenes, start=1):
        result = run_scene(scene, records, scenarios, scopes, gold)
        lines += render_scene(result, i, len(scenes), ink, gl, ask_text_mode)
    lines += footer(choice, len(scenes), len(records_list), ink, gl)
    return gl.sanitize(chr(10).join(lines))
